CREATE DATABASE `FINALDB`;

USE `FINALDB`;

CREATE TABLE USERS (
USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
USERNAME VARCHAR(255) UNIQUE NOT NULL,
ENCRYPTED_PASSWORD VARCHAR(255) NOT NULL,
FULL_NAME VARCHAR(255),
PHONE_NUMBER VARCHAR(45),
SEX VARCHAR(45),
BIRTHDAY DATE,
ADDRESS VARCHAR(255),
EMAIL VARCHAR(255),
AVATAR VARCHAR(255)
);

CREATE TABLE ROLES (
ROLE_ID BIGINT PRIMARY KEY,
ROLE_NAME VARCHAR(45)
);

CREATE TABLE USER_ROLE (
ID BIGINT PRIMARY KEY,
USER_ID bigint UNIQUE,
ROLE_ID bigint UNIQUE 
);

CREATE TABLE CATEGORY (
CATEGORY_ID BIGINT PRIMARY KEY,
CATEGORY_NAME VARCHAR(255)
);

CREATE TABLE PRODUCTS (
PRODUCT_ID BIGINT AUTO_INCREMENT primary Key,
CATEGORY_ID BIGINT,
PRODUCT_NAME VARCHAR(255),
PRODUCT_PRICE BIGINT,
QUANTITY INT,
PRODUCT_DESCRIPTION VARCHAR(512),
MAIN_PICTURE VARCHAR(255),
PICTURE1 VARCHAR(255),
PICTURE2 VARCHAR(255),
PICTURE3 VARCHAR(255),
CONSTRAINT PRODUCT_CATEGORY_FK1 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO `CATEGORY` (CATEGORY_ID, CATEGORY_NAME)
VALUES (1, 'Ao');
INSERT INTO `CATEGORY` (CATEGORY_ID, CATEGORY_NAME)
VALUES (2, 'Quan');

CREATE TABLE CART_ITEMS (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
PRODUCT_ID BIGINT,
USER_ID BIGINT,
QUANTITY INT,
	CONSTRAINT CART_ITEMS_FK1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CART_ITEMS_FK2 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

INSERT INTO `CART_ITEMS` (PRODUCT_ID, USER_ID, QUANTITY)
VALUES (1, 2, 1);
INSERT INTO `CART_ITEMS` (PRODUCT_ID, USER_ID, QUANTITY)
VALUES (4, 2, 1);

-- INSERT INTO `PRODUCTS` (PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, QUANTITY, PRODUCT_DESCRIPTION, MAIN_PICTURE)
-- VALUES (1, 1, 'CROSS THE STREET TEE', 310000, 100, 'Ao thoi trang', '
-- //bizweb.dktcdn.net/thumb/grande/100/318/614/products/wuntitled-5-01-6.jpg?v=1634791531000');
-- INSERT INTO `PRODUCTS` (PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, QUANTITY, PRODUCT_DESCRIPTION, MAIN_PICTURE)
-- VALUES (2, 1, '"MARCUS" THROUGH THE NIGHT TEE', 300000, 100, 'Ao thoi trang', '
-- //bizweb.dktcdn.net/thumb/grande/100/318/614/products/wuntitled-9-05-1.jpg?v=1627188886000');
-- INSERT INTO `PRODUCTS` (PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, QUANTITY, PRODUCT_DESCRIPTION, MAIN_PICTURE)
-- VALUES (3, 1, 'MONA "MARCUS" TEE', 325000, 100, 'Ao thoi trang', '
-- //bizweb.dktcdn.net/thumb/grande/100/318/614/products/wuntitled-1-06-8-compressed-1.jpg?v=1626880834000');

-- INSERT INTO `PRODUCTS` (PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, QUANTITY, PRODUCT_DESCRIPTION, MAIN_PICTURE)
-- VALUES (4, 2, 'JEANS CARGO PANTS', 406000, 100, 'Quan thoi trang', '
-- //bizweb.dktcdn.net/thumb/grande/100/318/614/products/wuntitled-4-04-3.jpg?v=1623408871000');
-- INSERT INTO `PRODUCTS` (PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, QUANTITY, PRODUCT_DESCRIPTION, MAIN_PICTURE)
-- VALUES (5, 2, 'WASH SWEATPANTS', 397000, 100, 'Quan thoi trang', '
-- //bizweb.dktcdn.net/thumb/grande/100/318/614/products/wuntitled-9-02-4.jpg?v=1622891553000');
-- INSERT INTO `PRODUCTS` (PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, QUANTITY, PRODUCT_DESCRIPTION, MAIN_PICTURE)
-- VALUES (6, 2, 'WASH SWEATSHORTS', 294000, 100, 'Quan thoi trang', '
-- //bizweb.dktcdn.net/thumb/grande/100/318/614/products/wuntitled-10-02-3.jpg?v=1623409413000');



-- CREATE TABLE ORDERS (
-- ORDER_ID bigint primary key,
-- USER_ID bigint,
-- DATE_ORDER datetime,
-- STATUS VARCHAR(255),
-- TOTAL_PRICE bigint
-- );

-- CREATE TABLE ORDERDETAILS(
-- ORDERDETAILS_ID bigint primary key,
-- ORDER_ID bigint,
-- PRODUCT_ID bigint
-- );

ALTER TABLE USER_ROLE
	ADD CONSTRAINT USER_ROLE_FK1 FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID);

ALTER TABLE USER_ROLE
	ADD CONSTRAINT USER_ROLE_FK2 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

CREATE TABLE PERSISTENT_LOGIN (
USERNAME VARCHAR(255) NOT NULL,
SERIES VARCHAR(64) NOT NULL PRIMARY KEY,
TOKEN VARCHAR(64) NOT NULL,
LAST_USED TIMESTAMP
);

INSERT INTO `ROLES` VALUES(1, 'ROLE_ADMIN');
INSERT INTO `ROLES` VALUES(2, 'ROLE_USER');

INSERT INTO `USER_ROLE` (ID, USER_ID, ROLE_ID)
VALUES (1, 1, 1);

-- INSERT INTO `USER_ROLE` (ID, USER_ID, ROLE_ID) -- Error Code: 1062. Duplicate entry '1' for key 'user_role.USER_ID'
-- VALUES (2, 1, 2);

INSERT INTO `USER_ROLE`(ID, USER_ID, ROLE_ID)
VALUES (2, 2, 2);

DROP TABLE `finaldb`.`cart_items`;
DROP TABLE `finaldb`.`products`;
DROP TABLE `finaldb`.`category`;